### ISSUE TITLE
non organizational onedrive account

### ISSUE THREAD

**Issue by ferypc** [hevelius/files_external_onedrive#40]
in manual, you said that
> Make sure to select:
> "Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)"

so, it won't work with non-office365 onedrive account?
i have one drive account with additional storage and using '@outlook.com' account username
while trying to grant access, this error appears

> We're unable to complete your request
> unauthorized_client: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.

any help appreciated
thank you

**Comment by prakhargahlot** [comment]
I am facing the same issue. However, I don't think it is because of a non-M365(formerly O365) account since the following phrase covers your (and my) usecase.

> and personal Microsoft accounts

I assume it has something to do with Nextcloud v18+ incompatibility. But yeah,

Any help would be welcome.

**Comment by tecnomaster** [comment]
Hi, I have the same problem as I want to use the 1TB free Onedrive storage for my personal outlook account as a Office365 user.

Please see this:
https://docs.microsoft.com/en-us/azure/active-directory/develop/supported-accounts-validation

The signInAudience property used by the app just allows AzureADMultipleOrgs and when I try to change the manifest to have that as AzureADandPersonalMicrosoftAccount or PersonalMicrosoftAccount, it can't be saved reporting the error: Property accessTokenAcceptedVersion is invalid.. [I6NzLtMiu4eUDJRCyvmxof].

I believe that the Oauth authentication for multipleorganizations just allows educational or business microsoft accounts but not personal accounts.

Does anyone has been able to go arround it?

Any help would be very appreciated.

P.D.: I am using nextcloud 19.X and I really believe the the problem is with the permisions approval from Microsoft.

**Comment by hevelius** [comment]
Hi, could be an issue releated with #43. Now resolved with latest release fo files_external_onedrive.

**Comment by Eothred** [comment]
I'm still having this issue with app version 1.0.9, should I open a new ticket?
